version: 1.0.{build}

platform: 
 - x86

clone_folder: c:\mgs

build_script:
 - ps: C:\mgs\build\build.ps1 -psyq_path4dot4 C:\psyq\psyq_4.4\bin -psyq_path4dot3 C:\psyq\psyq_4.3\bin
 
install:
 - git clone https://github.com/FoxdieTeam/psyq_sdk.git c:\psyq --depth 1
 - git submodule update --init --recursive

test: off
